modLoader="javafml"
loaderVersion="[43,)"
license="MIT"

[[mods]]
modId="boingboingitem"
version="0.2"
displayName="BoingBoing Item"
description='''
Items bounce like slimes when dropped on the ground!
'''

[[dependencies.boingboingitem]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.boingboingitem]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.20.5)"
ordering="NONE"
side="BOTH"
