modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="boingboingitem"
version="1.0.0"
displayName="BoingBoing Item"
description='''
Items bounce like slimes when dropped on the ground!
'''

[[dependencies.boingboingitem]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.boingboingitem]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
