modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
issueTrackerURL=""

[[mods]]
modId="boingboingitem"
version="1.0.0"
displayName="BoingBoing Item"
description='''
Items bounce like slimes when dropped on the ground!
'''

[[dependencies.boingboingitem]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.boingboingitem]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"
