modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL=""

[[mods]]
modId="boingboingitem"
version="0.2"
displayName="BoingBoing Item"
description='''
Items bounce like slimes when dropped on the ground!
'''

[[dependencies.boingboingitem]]
modId="neoforge"
type="required"
versionRange="[1,)"
ordering="NONE"
side="BOTH"

[[dependencies.boingboingitem]]
modId="minecraft"
type="required"
versionRange="[1.20.2,1.22)"
ordering="NONE"
side="BOTH"
